apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/cucp-core-n2
  name: cucp-core-n2
  namespace: oai-ran
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|example|cucp-core-n2'
spec:
  config: '{"cniVersion":"0.3.1","name": "cucp-core-n2","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/cucp-core-f1c
  name: cucp-core-f1c
  namespace: oai-ran
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|example|cucp-core-f1c'
spec:
  config: '{"cniVersion":"0.3.1","name": "cucp-core-f1c","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/cucp-core-e1
  name: cucp-core-e1
  namespace: oai-ran
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|example|cucp-core-e1'
spec:
  config: '{"cniVersion":"0.3.1","name": "cucp-core-e1","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
