apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: example/du-example
  name: du-edge
  namespace: oai-ran-du
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|example|du-example'
spec:
  provider: du.openairinterface.org
  interfaces:
  - name: f1
    ipv4:
      address: 192.168.32.4/24
      gateway: 192.168.32.1
    vlanID: 32
  parametersRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    name: oai-du-config
  - apiVersion: ref.nephio.org/v1alpha1
    kind: Config
    name: oai-cucp-config
