apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/du-edge-f1
  name: du-edge-f1
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|example|du-edge-f1'
spec:
  config: '{"cniVersion":"0.3.1","name": "du-edge-f1","plugins":[{"type":"macvlan","capabilities":{"ips":true}, "master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
