apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/cuup-edge-n3
  name: cuup-edge-n3
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|example|cuup-edge-n3'
spec:
  config: '{"cniVersion":"0.3.1","name": "cuup-edge-n3","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/cuup-edge-f1u
  name: cuup-edge-f1u
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|example|cuup-edge-f1u'
spec:
  config: '{"cniVersion":"0.3.1","name": "cuup-edge-f1u","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/cuup-edge-e1
  name: cuup-edge-e1
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|example|cuup-edge-e1'
spec:
  config: '{"cniVersion":"0.3.1","name": "cuup-edge-e1","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
